import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

const PRIMARY = '#2563EB'
const SECONDARY = '#7C3AED'

function addHeader(doc, title, subtitle) {
  doc.setFillColor(37, 99, 235)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('MoneyTalk', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(title, 14, 20)
  doc.setTextColor(50, 50, 50)
  doc.setFontSize(11)
  if (subtitle) doc.text(subtitle, 14, 36)
  return subtitle ? 44 : 36
}

function addSectionTitle(doc, text, y) {
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(100, 100, 100)
  doc.text(text.toUpperCase(), 14, y)
  doc.setDrawColor(220, 220, 220)
  doc.line(14, y + 2, 196, y + 2)
  return y + 10
}

function checkPage(doc, y, needed = 20) {
  if (y + needed > 280) {
    doc.addPage()
    return 20
  }
  return y
}

export function exportPersonalPDF(budget, expenses, activeMonth) {
  const doc = new jsPDF()
  const monthLabel = activeMonth
    ? new Date(activeMonth + '-01').toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })
    : 'Unknown Month'

  let y = addHeader(doc, 'Personal Finance Report', monthLabel)

  const totalAllocated = (budget.allocations || []).reduce((s, a) => s + Number(a.amount || 0), 0)
  const totalSpent = expenses.reduce((s, e) => s + Number(e.amount), 0)
  const remaining = budget.total - totalAllocated - totalSpent

  doc.setFillColor(245, 247, 250)
  doc.roundedRect(14, y, 55, 22, 3, 3, 'F')
  doc.roundedRect(77, y, 55, 22, 3, 3, 'F')
  doc.roundedRect(140, y, 56, 22, 3, 3, 'F')

  doc.setFontSize(8); doc.setTextColor(120, 120, 120); doc.setFont('helvetica', 'normal')
  doc.text('TOTAL BUDGET', 16, y + 7)
  doc.text('TOTAL SPENT', 79, y + 7)
  doc.text('REMAINING', 142, y + 7)

  doc.setFontSize(13); doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 30, 30)
  doc.text(`Rs.${budget.total.toLocaleString()}`, 16, y + 18)
  doc.text(`Rs.${totalSpent.toLocaleString()}`, 79, y + 18)
  doc.setTextColor(remaining >= 0 ? 16 : 239, remaining >= 0 ? 185 : 68, remaining >= 0 ? 129 : 68)
  doc.text(`Rs.${remaining.toLocaleString()}`, 142, y + 18)

  y += 30

  if (budget.allocations && budget.allocations.filter(a => a.label).length > 0) {
    y = checkPage(doc, y)
    y = addSectionTitle(doc, 'Fixed Allocations', y)
    doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(50, 50, 50)
    budget.allocations.filter(a => a.label).forEach(a => {
      y = checkPage(doc, y)
      doc.text(a.label, 16, y)
      doc.setFont('helvetica', 'bold')
      doc.text(`Rs.${Number(a.amount).toLocaleString()}`, 180, y, { align: 'right' })
      doc.setFont('helvetica', 'normal')
      y += 8
    })
    y += 4
  }

  if (expenses.length > 0) {
    y = checkPage(doc, y)
    y = addSectionTitle(doc, 'Expense Log', y)

    const grouped = expenses.reduce((acc, e) => {
      acc[e.date] = acc[e.date] || []
      acc[e.date].push(e)
      return acc
    }, {})

    Object.keys(grouped).sort().forEach(date => {
      y = checkPage(doc, y, 16)
      doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(37, 99, 235)
      doc.text(new Date(date).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long' }), 16, y)
      y += 6

      grouped[date].forEach(e => {
        y = checkPage(doc, y)
        doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(50, 50, 50)
        doc.text(e.item, 18, y)
        doc.setTextColor(120, 120, 120)
        doc.text(e.category, 120, y)
        doc.setFont('helvetica', 'bold'); doc.setTextColor(239, 68, 68)
        doc.text(`-Rs.${e.amount}`, 180, y, { align: 'right' })
        y += 7
      })

      const dayTotal = grouped[date].reduce((s, e) => s + e.amount, 0)
      doc.setFont('helvetica', 'bold'); doc.setTextColor(50, 50, 50); doc.setFontSize(9)
      doc.text(`Day Total: Rs.${dayTotal.toLocaleString()}`, 180, y, { align: 'right' })
      y += 10
    })
  }

  doc.setFontSize(8); doc.setTextColor(180, 180, 180); doc.setFont('helvetica', 'normal')
  doc.text(`Generated by MoneyTalk — ${new Date().toLocaleDateString('en-IN')}`, 14, 290)

  doc.save(`MoneyTalk_Personal_${activeMonth}.pdf`)
}

export function exportGroupPDF(group, groupExpenses, settlement) {
  const doc = new jsPDF()
  let y = addHeader(doc, 'Group Expense Report', group.name)

  doc.setFontSize(10); doc.setTextColor(100, 100, 100); doc.setFont('helvetica', 'normal')
  doc.text(`Members: ${group.members.join(', ')}`, 14, y)
  y += 8

  const total = groupExpenses.reduce((s, e) => s + e.amount, 0)
  doc.setFillColor(37, 99, 235)
  doc.roundedRect(14, y, 182, 18, 3, 3, 'F')
  doc.setTextColor(255, 255, 255); doc.setFontSize(9); doc.setFont('helvetica', 'normal')
  doc.text('TOTAL GROUP EXPENSES', 16, y + 7)
  doc.setFontSize(13); doc.setFont('helvetica', 'bold')
  doc.text(`Rs.${total.toLocaleString()}`, 16, y + 15)
  y += 26

  y = addSectionTitle(doc, 'Expense Log', y)
  const sorted = [...groupExpenses].sort((a, b) => new Date(a.date) - new Date(b.date))
  sorted.forEach(e => {
    y = checkPage(doc, y)
    doc.setFontSize(10); doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 30, 30)
    doc.text(e.desc, 16, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100); doc.setFontSize(9)
    doc.text(`${new Date(e.date).toLocaleDateString('en-IN')} · Paid by ${e.paidBy} · Split: ${e.splitAmong.join(', ')}`, 16, y + 6)
    doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 30, 30); doc.setFontSize(10)
    doc.text(`Rs.${e.amount.toLocaleString()}`, 180, y, { align: 'right' })
    y += 14
  })

  y = checkPage(doc, y, 40)
  y = addSectionTitle(doc, 'Settlement — Who Pays Whom', y)
  if (settlement.transactions.length === 0) {
    doc.setFontSize(11); doc.setTextColor(16, 185, 129); doc.setFont('helvetica', 'bold')
    doc.text('All settled!', 16, y)
    y += 10
  } else {
    settlement.transactions.forEach(t => {
      y = checkPage(doc, y)
      doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(50, 50, 50)
      doc.text(`${t.from}  owes  ${t.to}`, 16, y)
      doc.setFont('helvetica', 'bold')
      doc.text(`Rs.${t.amount.toLocaleString()}`, 180, y, { align: 'right' })
      y += 9
    })
  }

  doc.setFontSize(8); doc.setTextColor(180, 180, 180); doc.setFont('helvetica', 'normal')
  doc.text(`Generated by MoneyTalk — ${new Date().toLocaleDateString('en-IN')}`, 14, 290)
  doc.save(`MoneyTalk_Group_${group.name}.pdf`)
}

export function exportMultiAccessPDF(account, accExpenses, settlement) {
  const doc = new jsPDF()
  let y = addHeader(doc, 'Shared Account Report', account.name)

  doc.setFontSize(10); doc.setTextColor(100, 100, 100); doc.setFont('helvetica', 'normal')
  doc.text(`Members: ${account.members.join(', ')}`, 14, y)
  y += 8

  const totalSpent = accExpenses.reduce((s, e) => s + Number(e.amount), 0)
  const remaining = account.budget - totalSpent

  doc.setFillColor(245, 247, 250)
  doc.roundedRect(14, y, 86, 22, 3, 3, 'F')
  doc.roundedRect(110, y, 86, 22, 3, 3, 'F')
  doc.setFontSize(8); doc.setTextColor(120, 120, 120)
  doc.text('TOTAL BUDGET', 16, y + 7)
  doc.text('REMAINING', 112, y + 7)
  doc.setFontSize(13); doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 30, 30)
  doc.text(`Rs.${account.budget.toLocaleString()}`, 16, y + 18)
  doc.setTextColor(remaining >= 0 ? 16 : 239, remaining >= 0 ? 185 : 68, remaining >= 0 ? 129 : 68)
  doc.text(`Rs.${remaining.toLocaleString()}`, 112, y + 18)
  y += 30

  y = addSectionTitle(doc, 'Expense Log', y)
  const sorted = [...accExpenses].sort((a, b) => new Date(a.date) - new Date(b.date))
  sorted.forEach(e => {
    y = checkPage(doc, y)
    doc.setFontSize(10); doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 30, 30)
    doc.text(e.desc, 16, y)
    doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 100, 100); doc.setFontSize(9)
    doc.text(`${new Date(e.date).toLocaleDateString('en-IN')} · ${e.paidBy}`, 16, y + 6)
    doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 30, 30); doc.setFontSize(10)
    doc.text(`Rs.${Number(e.amount).toLocaleString()}`, 180, y, { align: 'right' })
    y += 14
  })

  y = checkPage(doc, y, 40)
  y = addSectionTitle(doc, 'Who Spent the Most', y)
  settlement.forEach(s => {
    y = checkPage(doc, y)
    doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(50, 50, 50)
    doc.text(s.member, 16, y)
    doc.setFont('helvetica', 'bold')
    doc.text(`Paid: Rs.${s.paid.toLocaleString()}`, 100, y)
    doc.setTextColor(s.owes > 0 ? 239 : 16, s.owes > 0 ? 68 : 185, s.owes > 0 ? 68 : 129)
    doc.text(s.owes > 0 ? `Owes: Rs.${s.owes}` : 'Settled', 160, y)
    y += 9
  })

  doc.setFontSize(8); doc.setTextColor(180, 180, 180); doc.setFont('helvetica', 'normal')
  doc.text(`Generated by MoneyTalk — ${new Date().toLocaleDateString('en-IN')}`, 14, 290)
  doc.save(`MoneyTalk_MultiAccess_${account.name}.pdf`)
}

// ✅ Now async to support html2canvas for chart capture
export async function exportMonthEndPDF(allMonths, selectedMonths, reportText) {
  const doc = new jsPDF()
  const getMonthLabel = (key) => new Date(key + '-01').toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })
  const getTotal = (key) => (allMonths[key]?.expenses || []).reduce((s, e) => s + Number(e.amount), 0)

  let y = addHeader(doc, 'Month End Summary Report', selectedMonths.map(getMonthLabel).join(' vs '))

  // Per-month breakdown
  selectedMonths.forEach(month => {
    const exps = allMonths[month]?.expenses || []
    const total = getTotal(month)
    y = checkPage(doc, y, 30)
    y = addSectionTitle(doc, getMonthLabel(month), y)

    doc.setFillColor(37, 99, 235)
    doc.roundedRect(14, y, 182, 16, 3, 3, 'F')
    doc.setTextColor(255, 255, 255); doc.setFontSize(9); doc.setFont('helvetica', 'normal')
    doc.text('TOTAL SPENT', 16, y + 6)
    doc.setFontSize(12); doc.setFont('helvetica', 'bold')
    doc.text(`Rs.${total.toLocaleString()}`, 16, y + 13)
    y += 24

    const categoryTotals = exps.reduce((acc, e) => {
      acc[e.category] = (acc[e.category] || 0) + Number(e.amount)
      return acc
    }, {})

    Object.entries(categoryTotals).sort((a, b) => b[1] - a[1]).forEach(([cat, amt]) => {
      y = checkPage(doc, y)
      doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(50, 50, 50)
      doc.text(cat, 18, y)
      doc.setFont('helvetica', 'bold')
      doc.text(`Rs.${amt.toLocaleString()}`, 180, y, { align: 'right' })
      y += 7
    })
    y += 8
  })

  // ✅ Capture and embed the compare chart
  const chartEl = document.getElementById('compare-chart')
  if (chartEl) {
    y = checkPage(doc, y, 100)
    y = addSectionTitle(doc, 'Spending Comparison Chart', y)
    try {
      const canvas = await html2canvas(chartEl, { backgroundColor: '#ffffff', scale: 2 })
      const imgData = canvas.toDataURL('image/png')
      doc.addImage(imgData, 'PNG', 14, y, 182, 80)
      y += 88
    } catch (e) {
      console.error('Chart capture failed:', e)
    }
  }

  // ✅ Spending analysis report text
  if (reportText) {
    y = checkPage(doc, y, 30)
    y = addSectionTitle(doc, 'Spending Analysis', y)
    const lines = reportText.split('\n')
    lines.forEach(line => {
      if (!line.trim()) { y += 3; return }
      y = checkPage(doc, y)
      const isHeader = line.startsWith('📊') || line.startsWith('📂') || line.startsWith('💸') || line.startsWith('📈') || line.startsWith('🆕') || line.startsWith('✅')
      doc.setFontSize(isHeader ? 10 : 9)
      doc.setFont('helvetica', isHeader ? 'bold' : 'normal')
      doc.setTextColor(isHeader ? 30 : 80, isHeader ? 30 : 80, isHeader ? 30 : 80)
      // Strip emojis for PDF since jsPDF doesn't render them
      const cleanLine = line.replace(/[\u{1F000}-\u{1FFFF}]/gu, '').replace(/📊|📂|💸|📈|🆕|✅/g, '').trim()
      const wrapped = doc.splitTextToSize(cleanLine, 176)
      wrapped.forEach(wl => {
        y = checkPage(doc, y)
        doc.text(wl, 16, y)
        y += isHeader ? 7 : 6
      })
    })
  }

  doc.setFontSize(8); doc.setTextColor(180, 180, 180); doc.setFont('helvetica', 'normal')
  doc.text(`Generated by MoneyTalk — ${new Date().toLocaleDateString('en-IN')}`, 14, 290)
  doc.save(`MoneyTalk_MonthEnd_Report.pdf`)
}